icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: codgramer
packager: codgramer
license: GPLv3
url: https://github.com/codgramer/Music-Mynd

requires:
  - mpv-libs
  - libappindicator

display_name: Music Mynd

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true